name: eyeBot
favicon: null
layout_spectrum: 0.13837
typography_spectrum: 0.63913
title: 'eyeBot, LLC'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030303'
    - '#b09b93'
    - '#615f5f'
    - '#242525'
  brandStrength: 0.5
  lightness: 0.5196250583976507
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
