name: eyeBot
favicon: null
layout_spectrum: 0.05632103746756911
typography_spectrum: 0.14168602880090475
title: 'eyeBot, LLC'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8951723873615265
  lightness: 0.5196250583976507
  saturation: 0.3170628626830876
  rhythmicContrast: 0.825722413836047
purpose: []
